stages:
    - containerize

container:
    stage: containerize
    image: docker:20
    services:
        - docker:20-dind
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
        - export TAG_NAME=$CI_REGISTRY_IMAGE:${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME}
        - docker build -t $TAG_NAME .
        - docker push $TAG_NAME
    only:
        - develop
        - main
        - tags
