stages:
  - containerize
  - deploy

container:
  stage: containerize
  image: docker:20
  services:
    - docker:20-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - export TAG_NAME=$CI_REGISTRY_IMAGE:${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME}
    - docker build -t $TAG_NAME .
    - docker push $TAG_NAME
  only:
    - develop
    - main
    - tags

deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add --no-cache wget
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - wget https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz
    - tar -xvf helm-v3.6.3-linux-amd64.tar.gz
    - mv linux-amd64/helm .
  script:
    - ./helm upgrade dealership-api ./charts/dealership-api --install
