apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production-v1
  namespace: cert-manager
spec:
  acme:
    email: letsencrypt@mymail.de
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production-v1
    solvers:
    - http01:
       ingress:
         class: nginx