apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: prod-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: prod-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
