apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" .Release.Name "api" | trunc 63 | quote }}
  labels:
    {{- include "dealership-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dealership-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dealership-api.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: gitlab
      containers:
        - name: dealership-api
          image: {{ .Values.image_name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
