apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{- printf "%s-%s" .Release.Name "api" | trunc 63 }}
  labels:
    app: dealership-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dealership-api
  template:
    metadata:
      labels:
        app: dealership-api
    spec:
      containers:
        - name: dealership-api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
