apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" .Release.Name "api" | trunc 63 | quote }}
  labels:
    app: dealership-api
  annotations: 
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production-v1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: dealership.selyslab.com
      http: 
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-%s" .Release.Name "api" | trunc 63 | quote }}
                port: 
                  name: http
  tls:
  - hosts:
    - dealership.selyslab.com
    secretName: dealership.selyslab.com-tls
