apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "migrations.fullname" . }}
  labels:
    {{- include "migrations.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production-v1
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: migrate/migrate
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/ash
            - -ecx
            - >-
              ../migrate \
                -path ../migrations/ \
                -database ${DATABASE_URL} \
                up
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysqlSecret.secretName }}
                  key: {{ .Values.mysqlSecret.key }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
