apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "migrations.fullname" . }}
  labels:
    {{- include "migrations.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "migrations.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "migrations.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/ash
            - -ecx
            - >-
              /usr/bin/migrate \
                -path /migrations/ \
                -database ${DATABASE_URL} \
                up
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysqlSecret.secretName }}
                  key: {{ .Values.mysqlSecret.key }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
