{{- if .Values.mongoSecret.create}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongoSecret.secretName}}
type: Opaque
data:
  {{ .Values.mongoSecret.key }}: {{ printf "mongodb://%s:%s@%s" .Values.mongoSecret.username .Values.mongodb.auth.rootPassword .Values.mongoSecret.databaseName | b64enc }}
{{- end}}