{{- if .Values.mongoSecret.create}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongoSecret.secretName}}
type: Opaque
data:
  {{ .Values.mongoSecret.key }}: mongodb://{{.Values.mongoSecret.username}}:{{.Values.mongodb.auth.rootPassword}}@{{.Values.mongoSecret.databaseName}}
{{- end}}