apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name "api" | trunc 63 | quote }}
  labels:
    {{- include "dealership-api.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "dealership-api.selectorLabels" . | nindent 4 }}
  ports:
    - targetPort: http
      port: 80
      protocol: TCP
    