apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name "api" | trunc 63 | quote }}
  labels:
    app: dealership-api
spec:
  selector:
    app: dealership-api
  ports:
    - targetPort: http
      port: 80
      protocol: TCP
    